### ISSUE TITLE
Minimal example code newline character missing

### ISSUE THREAD

**Issue by mrmp17** [MaJerle/lwshell#14]
In minimal example code, input string `const char* input_str = "mycmd param1 \"param 2 with space\"";` is missing a newline or carriage return character. Until one of these characters is detected by `lwshell_input` function, parsing will not begin and the `mycmd_fn` function in example will not run.
Changing the input string to `const char* input_str = "mycmd param1 \"param 2 with space\"\n";` (or `\r`) solves the issue and produces the expected behaviour.

**Comment by MaJerle** [comment]
Thanks for the report. Fixed.
