### ISSUE TITLE
Wrong parameter in init ex

### ISSUE THREAD

**Issue by FangXS-github** [MaJerle/lwshell#16]
```c
lwshellr_t
lwshell_init_ex(lwshell_t* lwobj) {
    lwobj = LWSHELL_GET_LWOBJ(NULL);                ///  should be:   lwobj = LWSHELL_GET_LWOBJ(lwobj);
    LWSHELL_MEMSET(lwobj, 0x00, sizeof(*lwobj));
    return lwshellOK;
}
```
*lwshell.c*   **line236**   should be: `lwobj = LWSHELL_GET_LWOBJ(lwobj);`

or `lwshell_init_ex`func will always operate default object`shell`;

Thanks...

**Comment by MaJerle** [comment]
Thanks, good catch.
https://github.com/MaJerle/lwshell/commit/704f996c0a4661d763e1887ad5f1b2ada63939e8
