### ISSUE TITLE
carriage return line feed while cmd handling

### ISSUE THREAD

**Issue by mgiaco** [MaJerle/lwshell#6]
Hi,

Really great simple shell but for me there is one handling really bad. So if as an example the user inputs some command (`calc`) using a terminal which gives /r/n at the end of the command then the input string looks like this

`calc 1 2/r/n`

So then in the handle function of calc i do some printing to the terminal. But after that /r and /n will be printed also i think that is not a behavior for everyone. 

So a quick fix for me was change parse input. And if the parser found some command i will ignore the output of CR or LF but maybe there is a better solution. 

best regards,
mathias

**Comment by MaJerle** [comment]
Why would you have `/r/n` and not `\r\n`?

**Comment by mgiaco** [comment]
Sorry i mean \r\n

**Comment by MaJerle** [comment]
OK I catch - so problem is that in this case you want to react only on `\n` and ignore `\r` character.
I think this can be solved with additional config macros to allow user to decide how to move forward.

**Comment by mgiaco** [comment]
yes, many thanks

**Comment by MaJerle** [comment]
Sorry, but I think this is the behavior that works now. Currently - when you get `\r` before `\n`, parser reacts already at `\r` and ignores `\n`, but for sure prints it back - prints everything that was on the input.

I suppose you want to remove LW_OUTPUT parts in this cases right?

```c
        switch (d[i]) {
            case LWSHELL_ASCII_CR: {
                LW_OUTPUT(lw, "\r");            // <-- this?
                prv_parse_input(lw);
                LWSHELL_RESET_BUFF(lw);
                break;
            }
            case LWSHELL_ASCII_LF: {
                LW_OUTPUT(lw, "\n");            // <-- this?
                prv_parse_input(lw);
                LWSHELL_RESET_BUFF(lw);
                break;
            }
```

**Comment by mgiaco** [comment]
yes exactly.
